remote_theme: just-the-docs/just-the-docs
title: Decision Tracker

# Aux links for the upper right navigation
aux_links:
  "View record on GitHub":
    - "//github.com/reub-the-cube/decisions"
aux_links_new_tab: true
